"""Create initial tables

Revision ID: 30a96be3d8f0
Revises: 
Create Date: 2025-11-08 09:51:30.779549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30a96be3d8f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('line_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('child', sa.Column('approx', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_child_line_key'), 'child', ['line_key'], unique=False)
    op.create_unique_constraint('uq_child_membership', 'child', ['family_id', 'person_id'])
    op.add_column('family', sa.Column('line_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('family', sa.Column('approx', sa.Boolean(), nullable=True))
    op.add_column('family', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('family', sa.Column('is_single_parent', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_family_is_single_parent'), 'family', ['is_single_parent'], unique=False)
    op.create_index(op.f('ix_family_line_key'), 'family', ['line_key'], unique=False)
    op.create_index(op.f('ix_family_source_id'), 'family', ['source_id'], unique=False)
    op.create_unique_constraint('uq_family_couple', 'family', ['source_id', 'husband_id', 'wife_id'])
    op.create_foreign_key(None, 'family', 'source', ['source_id'], ['id'])
    op.add_column('person', sa.Column('approx', sa.Boolean(), nullable=True))
    op.add_column('person', sa.Column('line_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('person', sa.Column('normalized_given', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('person', sa.Column('normalized_surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('person', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_person_birth_year'), 'person', ['birth_year'], unique=False)
    op.create_index(op.f('ix_person_line_key'), 'person', ['line_key'], unique=False)
    op.create_index(op.f('ix_person_normalized_given'), 'person', ['normalized_given'], unique=False)
    op.create_index(op.f('ix_person_normalized_surname'), 'person', ['normalized_surname'], unique=False)
    op.create_unique_constraint('uq_person_source_line', 'person', ['source_id', 'line_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_person_source_line', 'person', type_='unique')
    op.drop_index(op.f('ix_person_normalized_surname'), table_name='person')
    op.drop_index(op.f('ix_person_normalized_given'), table_name='person')
    op.drop_index(op.f('ix_person_line_key'), table_name='person')
    op.drop_index(op.f('ix_person_birth_year'), table_name='person')
    op.drop_column('person', 'birth_year')
    op.drop_column('person', 'normalized_surname')
    op.drop_column('person', 'normalized_given')
    op.drop_column('person', 'line_key')
    op.drop_column('person', 'approx')
    op.drop_constraint(None, 'family', type_='foreignkey')
    op.drop_constraint('uq_family_couple', 'family', type_='unique')
    op.drop_index(op.f('ix_family_source_id'), table_name='family')
    op.drop_index(op.f('ix_family_line_key'), table_name='family')
    op.drop_index(op.f('ix_family_is_single_parent'), table_name='family')
    op.drop_column('family', 'is_single_parent')
    op.drop_column('family', 'source_id')
    op.drop_column('family', 'approx')
    op.drop_column('family', 'line_key')
    op.drop_constraint('uq_child_membership', 'child', type_='unique')
    op.drop_index(op.f('ix_child_line_key'), table_name='child')
    op.drop_column('child', 'approx')
    op.drop_column('child', 'line_key')
    # ### end Alembic commands ###
