"""Add confidence columns to PageText

Revision ID: b1f2e3d4c5a6
Revises: 30a96be3d8f0
Create Date: 2025-11-08 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f2e3d4c5a6'
down_revision: Union[str, Sequence[str], None] = '30a96be3d8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add confidence tracking columns to PageText table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagetext', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('pagetext', sa.Column('line_confidences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove confidence tracking columns from PageText table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagetext', 'line_confidences')
    op.drop_column('pagetext', 'confidence')
    # ### end Alembic commands ###
